using SlimDX;
using System;
using System.Collections.Generic;

namespace Cliparts.SchlagDenStarLive.MainApp.GamePool {
    public class AvailableGames {

        public static Dictionary<string, Type> TypeList = new Dictionary<string, Type>{
            {"15", typeof(Fifteen)},
            {"1:30", typeof(OneThirthy)},
            {"7-Meter-Werfen", typeof(SiebenMeterWerfen)},
            {"Abkürzung", typeof(Abkuerzung)},
            {"Ablenken", typeof(Ablenken)},
            {"Abrollen", typeof(Abrollen)},
            {"Abwerfen", typeof(Abwerfen)},
            {"Alphabetisch schreiben", typeof(AlphabetischSchreiben)},
            {"Am Rad drehen", typeof(AmRadDrehen)},
            {"Anders denken", typeof(AndersDenken)},
            {"Angry Birds", typeof(AngryBirds)},
            {"Anhängen", typeof(Anhaengen)},
            {"Anhänger", typeof(Anhaenger)},
            {"Anhänger-Stapel", typeof(AnhaengerStapel)},
            {"Auffangen", typeof(Auffangen)},
            {"Aufhängen", typeof(Aufhaengen)},
            {"Aufkleben", typeof(Aufkleben)},
            {"Augen", typeof(Augen)},
            {"Augen zählen", typeof(AugenZaehlen)},
            {"Aunt Sally", typeof(AuntSally)},
            {"Ausbalancieren", typeof(Ausbalancieren)},
            {"Ausbuzzern", typeof(Ausbuzzern)},
            {"Ausliefern", typeof(Ausliefern)},
            {"Ausrollen", typeof(Ausrollen)},
            {"Autoball", typeof(Autoball)},
            {"Auto-Basketball", typeof(AutoBasketball)},
            {"Autocross", typeof(Autocross)},
            {"Auto-Parcours", typeof(AutoParcours)},
            {"Autos", typeof(Autos)},
            {"Autoscooter-Ball", typeof(AutoscooterBall)},
            {"Auto-Springen", typeof(AutoSpringen)},
            {"Autos ziehen", typeof(AutosZiehen)},
            {"Axtwerfen", typeof(Axtwerfen)},
            {"Badminton", typeof(Badminton)},
            {"Badminton-Duell", typeof(BadmintonDuell)},
            {"Badminton-Maschine", typeof(BadmintonMaschine)},
            {"Bälle fangen", typeof(BaelleFangen)},
            {"Bäume aufstellen", typeof(BaeumeAufstellen)},
            {"Bäume fällen", typeof(BaeumeFaellen)},
            {"Bagger-Pendel", typeof(BaggerPendel)},
            {"Bagger-Puzzle", typeof(BaggerPuzzle)},
            {"Bagger-Staffel", typeof(BaggerStaffel)},
            {"Balance", typeof(Balance)},
            {"Balance-Loch", typeof(BalanceLoch)},
            {"Balancieren", typeof(Balancieren)},
            {"Balancier-Rohr", typeof(BalancierRohr)},
            {"BallBall", typeof(BallBall)},
            {"Ballerburg", typeof(Ballerburg)},
            {"Ballgefühl", typeof(Ballgefuehl)},
            {"Ball halten", typeof(BallHalten)},
            {"Ball ins Glas", typeof(BallInsGlas)},
            {"Ballon-Bagger", typeof(BallonBagger)},
            {"Ballon-Becher", typeof(BallonBecher)},
            {"Ballon-Blasrohr", typeof(BallonBlasrohr)},
            {"Ballon-Hüpfen", typeof(BallonHuepfen)},
            {"Ballons stechen", typeof(BallonsStechen)},
            {"Ballons wegräumen", typeof(BallonsWegraeumen)},
            {"Ball-Rampe", typeof(BallRampe)},
            {"Ball rollen", typeof(BallRollen)},
            {"Bankball", typeof(Bankball)},
            {"Bankdrücken", typeof(Bankdruecken)},
            {"Bankhüpfen", typeof(Bankhuepfen)},
            {"Barren", typeof(Barren)},
            {"Baseball-Wippe", typeof(BaseballWippe)},
            {"Basketball-Duell", typeof(BasketballDuell)},
            {"Basketball-Katapult", typeof(BasketballKatapult)},
            {"Basketball-Mütze", typeof(BasketballMuetze)},
            {"Baum abschmücken", typeof(BaumAbschmuecken)},
            {"Baum schmücken", typeof(BaumSchmuecken)},
            {"Baumstamm werfen", typeof(BaumstammWerfen)},
            {"Beachball", typeof(Beachball)},
            {"Beachminton", typeof(Beachminton)},
            {"Beachsoccer", typeof(Beachsoccer)},
            {"Beachtennis", typeof(Beachtennis)},
            {"Beachvolleyball", typeof(Beachvolleyball)},
            {"Becherball", typeof(Becherball)},
            {"Becherhüpfen", typeof(Becherhuepfen)},
            {"Becher Tic Tac Toe", typeof(BecherTicTacToe)},
            {"Becher treffen", typeof(BecherTreffen)},
            {"Besenlauf", typeof(Besenlauf)},
            {"Bierdeckel", typeof(Bierdeckel)},
            {"Bierdeckel-Haus", typeof(BierdeckelHaus)},
            {"Bilder aufhängen", typeof(BilderAufhaengen)},
            {"Billard", typeof(Billard)},
            {"Blamieren oder Kassieren", typeof(BlamierenOderKassieren)},
            {"Blamieren oder Kassieren 100", typeof(BlamierenOderKassieren100)},
            {"Blasebalg", typeof(Blasebalg)},
            {"Blasrohr", typeof(Blasrohr)},
            {"Blind fahren", typeof(BlindFahren)},
            {"Blind füllen", typeof(BlindFuellen)},
            {"Blind pinnen", typeof(BlindPinnen)},
            {"Blind puzzeln", typeof(BlindPuzzeln)},
            {"Blind schieben", typeof(BlindSchieben)},
            {"Bohren", typeof(Bohren)},
            {"Bogenlauf", typeof(Bogenlauf)},
            {"Bowling", typeof(Bowling)},
            {"Boxen", typeof(Boxen)},
            {"Brettminton", typeof(Brettminton)},
            {"Broomball", typeof(Broomball)},
            {"Bubble Football", typeof(BubbleFootball)},
            {"Buchstaben", typeof(Buchstaben)},
            {"Buckelpiste", typeof(Buckelpiste)},
            {"Bücher-Rennen", typeof(BuecherRennen)},
            {"Bügel fangen", typeof(BuegelFangen)},
            {"Buggy-Rennen", typeof(BuggyRennen)},
            {"Bullenreiten", typeof(Bullenreiten)},
            {"Bumper Boat", typeof(BumperBoat)},
            {"Bumper Cars", typeof(BumperCars)},
            {"Bumper-Duell", typeof(BumperDuell)},
            {"Cage-Soccer", typeof(CageSoccer)},
            {"Carambowl", typeof(Carambowl)},
            {"Catwalk", typeof(Catwalk)},
            {"Chippen", typeof(Chippen)},
            {"City-Rennen", typeof(CityRennen)},
            {"Climball", typeof(Climball)},
            {"Coconut Shy", typeof(CoconutShy)},
            {"Coinhole", typeof(Coinhole)},
            {"Cornhole", typeof(Cornhole)},
            {"Crazy-Carts", typeof(CrazyCarts)},
            {"Crossminton", typeof(Crossminton)},
            {"Das Laufrad", typeof(DasLaufrad)},
            {"Das Lochbrett", typeof(DasLochbrett)},
            {"Das Pendel", typeof(DasPendel)},
            {"Das Rad", typeof(DasRad)},
            {"Das Reck", typeof(DasReck)},
            {"Das Schloss", typeof(DasSchloss)},
            {"Das Sparschwein", typeof(DasSparschwein)},
            {"Das Tor", typeof(DasTor)},
            {"Das Wasserrad", typeof(DasWasserrad)},
            {"Deckeln", typeof(Deckeln)},
            {"Default", typeof(Default)},
            {"Der Holzturm", typeof(DerHolzturm)},
            {"Der Jägerzaun", typeof(DerJaegerzaun)},
            {"Der Kran", typeof(DerKran)},
            {"Der Mühlstein", typeof(DerMuehlstein)},
            {"Der Pärchen-Zaun", typeof(DerPaerchenZaun)},
            {"Der Raum", typeof(DerRaum)},
            {"Der Ring", typeof(DerRing) },
            {"Der schwebende Ball", typeof(DerSchwebendeBall) },
            {"Der schwere Draht", typeof(DerSchwereDraht)},
            {"Der Strohhalm", typeof(DerStrohhalm)},
            {"Der Türrahmen", typeof(DerTuerrahmen)},
            {"Der Tunnel", typeof(DerTunnel)},
            {"Der Zaun", typeof(DerZaun)},
            {"Deutschland-Holland", typeof(DeutschlandHolland)},
            {"Die erste Zeile", typeof(DieErsteZeile)},
            {"Die Küche", typeof(DieKueche)},
            {"Die Mauer", typeof(DieMauer)},
            {"Die Münze", typeof(DieMuenze)},
            {"Die Samstagsmaler", typeof(DieSamstagsmaler)},
            {"Die Scheibe", typeof(DieScheibe)},
            {"Die Seilbahn", typeof(DieSeilbahn)},
            {"Die Theke", typeof(DieTheke)},
            {"Die Torwand", typeof(DieTorwand)},
            {"Die Wand", typeof(DieWand)},
            {"Dinner for One", typeof(DinnerForOne)},
            {"Discgolf", typeof(Discgolf)},
            {"Doppel-Fehler", typeof(DoppelFehler)},
            {"Doppelhaushälfte", typeof(Doppelhaushaelfte)},
            {"Doppel-Säge", typeof(DoppelSaege)},
            {"Doppel-Schlitten", typeof(DoppelSchlitten)},
            {"Dosen-Frisbee", typeof(DosenFrisbee)},
            {"Dosen-Karussel", typeof(DosenKarussel)},
            {"Dosenlaufen", typeof(Dosenlaufen)},
            {"Dosen öffnen", typeof(DosenOeffnen)},
            {"Dosenwerfen", typeof(Dosenwerfen)},
            {"Dosen zertreten", typeof(DosenZertreten)},
            {"Double Disc Court", typeof(DoubleDiscCourt)},
            {"Draisinathlon", typeof(Draisinathlon)},
            {"Draisinen-Auto", typeof(DraisinenAuto)},
            {"Dreh-Platte", typeof(DrehPlatte)},
            {"Drumometer", typeof(Drumometer)},
            {"Drunter und drüber", typeof(DrunterUndDrueber)},
            {"Drehrohr", typeof(Drehrohr)},
            {"3 oder 4?", typeof(DreiOderVier)},
            {"Drei-Sprung", typeof(DreiSprung)},
            {"Dreisprung", typeof(Dreisprung)},
            {"Drift-Kart", typeof(DriftKart)},
            {"Drift-Kart Stechen", typeof(DriftKartStechen)},
            {"Drift-Rider", typeof(DriftRider)},
            {"Drift-Rider Stechen", typeof(DriftRiderStechen)},
            {"Drifttrike", typeof(Drifttrike)},
            {"Drive-By", typeof(DriveBy)},
            {"drop it", typeof(DropIt)},
            {"Duft-Pärchen", typeof(DuftPaerchen)},
            {"Durch die Wand", typeof(DurchDieWand)},
            {"Durchhauen", typeof(Durchhauen)},
            {"Durch-Ball", typeof(DurchBall)},
            {"Durchrollen", typeof(Durchrollen)},
            {"Durchsägen", typeof(Durchsaegen)},
            {"Easy Rider", typeof(EasyRider)},
            {"Ecken-Ball", typeof(EckenBall)},
            {"Ecke, Tor", typeof(EckeTor)},
            {"E-Gokart", typeof(EGokart)},
            {"E-Gokart Stechen", typeof(EGokartStechen)},
            {"Eier auspusten", typeof(EierAuspusten)},
            {"Eierlauf", typeof(Eierlauf)},
            {"Eier suchen", typeof(EierSuchen)},
            {"Eimer-Ball", typeof(EimerBall)},
            {"Ein-Bechern", typeof(EinBechern)},
            {"Einfüllen", typeof(Einfuellen)},
            {"Einhaken", typeof(Einhaken)},
            {"Einhand-Tischtennis", typeof(EinhandTischtennis)},
            {"Einkaufswagen", typeof(Einkaufswagen)},
            {"Einkaufswagen parken", typeof(EinkaufswagenParken)},
            {"Einparken", typeof(Einparken)},
            {"Einschätzen & Abliefern", typeof(EinschaetzenUndAbliefern)},
            {"Eintreten", typeof(Eintreten)},
            {"Eisenbahn", typeof(Eisenbahn)},
            {"Eisfußball", typeof(Eisfussball)},
            {"Eis-Penaltyschießen", typeof(EisPenaltyschiessen)},
            {"Eis-Quadtrathlon", typeof(EisQuadtrathlon)},
            {"Eis-Rad-Rennen", typeof(EisRadRennen)},
            {"Englisch-Golf", typeof(EnglischGolf)},
            {"Entenangeln", typeof(Entenangeln)},
            {"Eisstockschießen", typeof(Eisstockschiessen)},
            {"Entweder, oder", typeof(EntwederOder)},
            {"E-Scooter", typeof(EScooter)},
            {"Faden essen", typeof(FadenEssen)},
            {"Fahrrad-Bowling", typeof(FahrradBowling)},
            {"Fahrrad-Bumping", typeof(FahrradBumping)},
            {"Fahrrad-Polo-Slalom", typeof(FahrradPoloSlalom)},
            {"Fahr-Wippe", typeof(FahrWippe)},
            {"Fallen lassen", typeof(FallenLassen)},
            {"Fang den Hut", typeof(FangDenHut)},
            {"Farben-Würfel", typeof(FarbenWuerfel)},
            {"Fechten", typeof(Fechten)},
            {"Fehlerbilder", typeof(Fehlerbilder)},
            {"Fehlerduell", typeof(Fehlerduell)},
            {"Fenster-Badminton", typeof(FensterBadminton)},
            {"Festkleben", typeof(Festkleben)},
            {"Feuerwerk", typeof(Feuerwerk)},
            {"Fidget Spinner", typeof(FidgetSpinner)},
            {"Fieldgoal", typeof(Fieldgoal)},
            {"Filmplakate", typeof(Filmplakate)},
            {"Finger-Football", typeof(FingerFootball)},
            {"Fitnessband", typeof(Fitnessband)},
            {"Fitnessband-Staffel", typeof(FitnessbandStaffel)},
            {"Flaggen malen", typeof(FlaggenMalen)},
            {"Flaschen aufstellen", typeof(FlaschenAufstellen)},
            {"Flaschenangeln", typeof(Flaschenangeln)},
            {"Flasche werfen", typeof(FlascheWerfen)},
            {"Flieger", typeof(Flieger)},
            {"Flohhüpfen", typeof(Flohhuepfen)},
            {"Floorball", typeof(Floorball)},
            {"Fragen-Duell", typeof(FragenDuell)},
            {"Frauenfußball", typeof(Frauenfussball)},
            {"Fremdsprachen", typeof(Fremdsprachen)},
            {"Frisbee-Duell", typeof(FrisbeeDuell)},
            {"Frisbee-Parcour", typeof(FrisbeeParcour)},
            {"Friss die Hälfte", typeof(FrissDieHaelfte)},
            {"Fühlen", typeof(Fuehlen) },
            {"Fußball-Minigolf", typeof(FussballMinigolf)},
            {"Fußball-Penalty", typeof(FussballPenalty)},
            {"Fußball Tic Tac Toe", typeof(FussballTicTacToe)},
            {"Fußball-Tunnel", typeof(FussballTunnel)},
            {"Fußball-Wappen", typeof(FussballWappen)},
            {"Gebärdensprache", typeof(Gebaerdensprache)},
            {"Gedankenlesen", typeof(Gedankenlesen)},
            {"Geländefahrzeug", typeof(Gelaendefahrzeug)},
            {"Geheimsprache", typeof(Geheimsprache)},
            {"Gepäckwagen", typeof(Gepaeckwagen)},
            {"Gepäckwagen Tiebreak", typeof(GepaeckwagenTiebreak)},
            {"Gewichte sortieren", typeof(GewichteSortieren)},
            {"Gleich-Laufen", typeof(GleichLaufen)},
            {"Glitch-Fußball", typeof(GlitchFussball)},
            {"Goalball", typeof(Goalball)},
            {"Golf-Darts", typeof(GolfDarts)},
            {"Golfkart", typeof(Golfkart)},
            {"Gravitations-Ball", typeof(GravitationsBall)},
            {"Greifen", typeof(Greifen)},
            {"Gummis flitschen", typeof(GummisFlitschen)},
            {"Haare", typeof(Haare) },
            {"Haidong Gumdo", typeof(HaidongGumdo)},
            {"Halbieren", typeof(Halbieren)},
            {"Halten", typeof(Halten)},
            {"Hammerwerfen", typeof(Hammerwerfen)},
            {"Handball", typeof(Handball)},
            {"Handball-Duell", typeof(HandballDuell)},
            {"Handbike", typeof(Handbike)},
            {"Handfußball-Duell", typeof(HandfussballDuell)},
            {"Handstand-Schalter", typeof(HandstandSchalter)},
            {"Hauptstadt-Duell", typeof(HauptstadtDuell)},
            {"Headis", typeof(Headis)},
            {"Helium-Rennen", typeof(HeliumRennen)},
            {"HesherBall", typeof(HesherBall)},
            {"Hindernisrennen", typeof(Hindernisrennen)},
            {"Hits auf Deutsch", typeof(HitsAufDeutsch)},
            {"Hitster", typeof(Hitster)},
            {"Hobeln", typeof(Hobeln)},
            {"Hobeln & Sammeln", typeof(HobelnUndSammeln)},
            {"Hochdruckreiniger", typeof(Hochdruckreiniger)},
            {"Hochseilgarten", typeof(Hochseilgarten)},
            {"Hochrollen", typeof(Hochrollen)},
            {"Hochseil-Rennen", typeof(HochseilRennen)},
            {"Hochundrunterwerfen", typeof(Hochundrunterwerfen)},
            {"Hochwandschießen", typeof(Hochwandschiessen)},
            {"Hochwerfen", typeof(Hochwerfen)},
            {"Hochziehen", typeof(Hochziehen)},
            {"Hockey", typeof(Hockey)},
            {"Höher werfen", typeof(HoeherWerfen)},
            {"Hör-Duell", typeof(HoerDuell)},
            {"Hören", typeof(Hoeren)},
            {"Holzhacken", typeof(Holzhacken)},
            {"Holz spalten", typeof(HolzSpalten)},
            {"Hot Rods", typeof(HotRods)},
            {"Hover-Kart", typeof(HoverKart)},
            {"Hubwagen", typeof(Hubwagen)},
            {"Hüftschwung", typeof(Hueftschwung)},
            {"Hüpf-Fußball", typeof(HuepfFussball)},
            {"Hürdenlauf", typeof(Huerdenlauf)},
            {"Hütchenspiel", typeof(Huetchenspiel)},
            {"Hunde anlocken", typeof(HundeAnlocken)},
            {"Inliner", typeof(Inliner)},
            {"Jahresrückblick", typeof(Jahresrueckblick)},
            {"Jakkolo", typeof(Jakkolo)},
            {"Kabelsalat", typeof(Kabelsalat)},
            {"Kabel ziehen", typeof(KabelZiehen)},
            {"Käsekästchen", typeof(Kaesekaestchen)},
            {"Käse reiben", typeof(KaeseReiben)},
            {"Kästen", typeof(Kaesten)},
            {"Kakerlakak", typeof(Kakerlakak)},
            {"Kanu-Rennen", typeof(KanuRennen)},
            {"Karatôn", typeof(Karaton)},
            {"Kart-Duell", typeof(KartDuell)},
            {"Kart-Duell Tiebreak", typeof(KartDuellTiebreak)},
            {"Kartfahren", typeof(Kartfahren)},
            {"Karussel-Ball", typeof(KarusselBall)},
            {"Katamino", typeof(Katamino)},
            {"Kegel wegschwingen", typeof(KegelWegschwingen)},
            {"Kehren", typeof(Kehren)},
            {"Kellen", typeof(Kellen)},
            {"Kennen", typeof(Kennen)},
            {"Kerzen anzünden", typeof(KerzenAnzuenden)},
            {"Kerzen ausblasen", typeof(KerzenAusblasen)},
            {"Kerzen ausschlagen", typeof(KerzenAusschlagen)},
            {"Kerzen aussprühen", typeof(KerzenAusspruehen)},
            {"Kerzenglocke", typeof(Kerzenglocke)},
            {"Kescher-Ball", typeof(KescherBall)},
            {"Kinofilme", typeof(Kinofilme)},
            {"Kickern", typeof(Kickern)},
            {"Kissenschlacht", typeof(Kissenschlacht)},
            {"Kisten halten", typeof(KistenHalten)},
            {"Klackerball", typeof(Klackerball)},
            {"Klackern", typeof(Klackern)},
            {"Klammern", typeof(Klammern)},
            {"Klapp-Kugel", typeof(KlappKugel)},
            {"Klask", typeof(Klask)},
            {"Kleben", typeof(Kleben)},
            {"Kleiderbügel", typeof(Kleiderbuegel)},
            {"Klötze halten", typeof(KloetzeHalten)},
            {"Klötze stapeln", typeof(KloetzeStapeln)},
            {"Klopapier", typeof(Klopapier)},
            {"Klotzen", typeof(Klotzen)},
            {"Knabbern", typeof(Knabbern)},
            {"Knobeln", typeof(Knobeln)},
            {"Knoten", typeof(Knoten)},
            {"Körbe werfen", typeof(KoerbeWerfen)},
            {"Kofferraum", typeof(Kofferraum)},
            {"Kopf-Ball", typeof(KopfBall)},
            {"Kopfüber werfen", typeof(KopfueberWerfen)},
            {"Kreisel-Slalom", typeof(KreiselSlalom)},
            {"Kronkorken knicken", typeof(KronkorkenKnicken)},
            {"Kürbis-Duell", typeof(KuerbisDuell)},
            {"Kugel-Balance", typeof(KugelBalance)},
            {"Kugelbett", typeof(Kugelbett)},
            {"Kugeln fangen", typeof(KugelnFangen)},
            {"Kugel-Puck", typeof(KugelPuck)},
            {"Kugel-Roulette", typeof(KugelRoulette)},
            {"Kugelstoßen", typeof(Kugelstossen)},
            {"Kugel-Strecke", typeof(KugelStrecke)},
            {"Kurbelauto", typeof(Kurbelauto)},
            {"Kurbelauto-Arena", typeof(KurbelautoArena)},
            {"Kurbelboot", typeof(Kurbelboot)},
            {"Lacrosse", typeof(Lacrosse)},
            {"Länder drehen", typeof(LaenderDrehen)},
            {"Länderkunde", typeof(Laenderkunde)},
            {"Länderpuzzle", typeof(Laenderpuzzle)},
            {"Länder schieben", typeof(LaenderSchieben)},
            {"Landeanflug", typeof(Landeanflug)},
            {"Langer Hammer", typeof(LangerHammer)},
            {"Lastenrad", typeof(Lastenrad)},
            {"Latten-Lauf", typeof(LattenLauf)},
            {"Lattlschießen", typeof(Lattlschießen)},
            {"Laubbläserball", typeof(Laubblaeserball)},
            {"Laufrad-Duell", typeof(LaufradDuell)},
            {"Leitergolf", typeof(Leitergolf)},
            {"Leiter-Slalom", typeof(LeiterSlalom)},
            {"Leitersprossen", typeof(Leitersprossen)},
            {"Leitfaden", typeof(Leitfaden)},
            {"Lenk-Labyrinth", typeof(LenkLabyrinth)},
            {"Lianen", typeof(Lianen)},
            {"Lichtschalter", typeof(Lichtschalter)},
            {"Lieder gurgeln", typeof(LiederGurgeln)},
            {"Lineal fallenlassen", typeof(LinealFallenlassen)},
            {"Löffel-Katapult", typeof(LoeffelKatapult)},
            {"Loslassen", typeof(Loslassen)},
            {"Luftballon", typeof(Luftballon)},
            {"Luftballon-Lauf", typeof(LuftballonLauf)},
            {"Luftballon-Party", typeof(LuftballonParty)},
            {"Luftballons platzen", typeof(LuftballonsPlatzen)},
            {"Luftlinie", typeof(Luftlinie)},
            {"Luftpolster", typeof(Luftpolster)},
            {"Luftschlangen", typeof(Luftschlangen)},
            {"Magnetkette", typeof(Magnetkette)},
            {"Magnet-Rennen", typeof(MagnetRennen)},
            {"Masken-Memory", typeof(MaskenMemory)},
            {"Maskottchen", typeof(Maskottchen)},
            {"Medizinball-Hochwurf", typeof(MedizinballHochwurf)},
            {"Medizinball-Rollen", typeof(MedizinballRollen)},
            {"Medizinbasketball", typeof(Medizinbasketball)},
            {"Meinungsforschung", typeof(Meinungsforschung)},
            {"Memory-Duell", typeof(MemoryDuell)},
            {"Menschenkenntnis", typeof(Menschenkenntnis)},
            {"Meraner Tischkegeln", typeof(MeranerTischkegeln)},
            {"Metalldetektor", typeof(Metalldetektor)},
            {"Mini-Tennis", typeof(MiniTennis)},
            {"Modelabel", typeof(Modelabel)},
            {"Moderner Zweikampf", typeof(ModernerZweikampf)},
            {"Mölkky", typeof(Moelkky)},
            {"Müllabfuhr", typeof(Muellabfuhr)},
            {"Münze drehen", typeof(MuenzeDrehen)},
            {"Münze ins Glas", typeof(MuenzeInsGlas)},
            {"Münze rollen", typeof(MuenzeRollen)},
            {"Multi-Korb", typeof(MultiKorb)},
            {"Musikinstrumente", typeof(Musikinstrumente)},
            {"Musik-Memory", typeof(MusikMemory)},
            {"Musik rückwärts", typeof(MusikRueckwaerts)},
            {"Musikvideos", typeof(Musikvideos)},
            {"Nachbauen", typeof(Nachbauen)},
            {"Nägel ziehen", typeof(NaegelZiehen)},
            {"Nähen", typeof(Naehen)},
            {"Nageln-Zweikampf", typeof(NagelnZweikampf)},
            {"Nicht Berühren!", typeof(NichtBeruehren)},
            {"Nippel-Memory", typeof(NippelMemory)},
            {"Original und Fälschung", typeof(OriginalUndFaelschung)},
            {"Pärchen finden", typeof(PaerchenFinden)},
            {"Pärchen gesucht", typeof(PaerchenGesucht)},
            {"Passen", typeof(Passen)},
            {"Parallel-Stapler", typeof(ParallelStapler)},
            {"Passe-Trappe", typeof(PasseTrappe)},
            {"Patschehändchen", typeof(Patschehaendchen)},
            {"Pfannenwurf", typeof(Pfannenwurf)},
            //{"Passen", typeof(Passen)},
            //{"Passen XL", typeof(PassenXL)},
            {"Pickleball", typeof(Pickleball)},
            {"Pickup-Parcour", typeof(PickupParcour)},
            {"Pit-Pat", typeof(PitPat)},
            {"Prellball", typeof(Prellball)},
            {"Publikumsstimmen", typeof(Publikumsstimmen)},
            {"Pumptrack", typeof(Pumptrack)},
            {"Pumptrack Tiebreak", typeof(PumptrackTiebreak)},
            {"Puste-Hügel", typeof(PusteHuegel)},
            {"Pusten", typeof(Pusten)},
            {"Puste-Rennen", typeof(PusteRennen)},
            {"Puste-Rohr", typeof(PusteRohr)},
            {"Puste-Tisch", typeof(PusteTisch)},
            {"Putten", typeof(Putten)},
            {"Pylonen-Darts", typeof(PylonenDarts)},
            {"Pylonen-Flip", typeof(PylonenFlip)},
            {"Pylonen Tic Tac Toe", typeof(PylonenTicTacToe)},
            {"Quad Fat Bike", typeof(QuadFatBike)},
            {"Räuberleiter", typeof(Raeuberleiter)},
            {"Rampen-Ball", typeof(RampenBall)},
            {"Rasenmäher parken", typeof(RasenmaeherParken)},
            {"Rasensprenger", typeof(Rasensprenger)},
            {"Rausholen", typeof(Rausholen)},
            {"Reaktions-Ball", typeof(ReaktionsBall)},
            {"Reaktions-Duell", typeof(ReaktionsDuell)},
            {"Reaktionswand ferngesteuert", typeof(ReaktionswandFerngesteuert)},
            {"Rechenzeichen", typeof(Rechenzeichen)},
            {"Reck-Drehung", typeof(ReckDrehung)},
            {"Reifen", typeof(Reifen)},
            {"Reifen-Rennen", typeof(ReifenRennen)},
            {"Reifen Tic Tac Toe", typeof(ReifenTicTacToe)},
            {"Reifen wenden", typeof(ReifenWenden)},
            {"Rein und raus", typeof(ReinUndRaus)},
            {"Rennball", typeof(Rennball)},
            {"Renn-Rechnen", typeof(RennRechnen)},
            {"Riech-Duell", typeof(RiechDuell)},
            {"Riechen", typeof(Riechen)},
            {"Ringe hangeln", typeof(RingeHangeln)},
            {"Ringe-Rampe", typeof(RingeRampe)},
            {"Ringe sammeln", typeof(RingeSammeln)},
            {"Ringe-Stapler", typeof(RingeStapler)},
            {"Ringing the Bullchen", typeof(RingingTheBullchen)},
            {"Ringing The Bulls", typeof(RingingTheBulls)},
            {"Ringstechen", typeof(Ringstechen)},
            {"Road Tennis", typeof(RoadTennis)},
            {"Röhren", typeof(Roehren)},
            {"Rohrhammer", typeof(Rohrhammer)},
            {"Rollen lassen", typeof(RollenLassen)},
            {"Roller-Rennen", typeof(RollerRennen)},
            {"Roller-Slalom", typeof(RollerSlalom)},
            {"Rollhockey", typeof(Rollhockey)},
            {"Rotieren", typeof(Rotieren)},
            {"Rovo-Schnecke", typeof(RovoSchnecke)},
            {"RowCart", typeof(RowCart)},
            {"Rubik's Race", typeof(RubiksRace)},
            {"Rüberwerfen", typeof(Rueberwerfen)},
            {"Rücken schreiben", typeof(RueckenSchreiben)},
            {"Rückwärts aufsagen", typeof(RueckwaertsAufsagen)},
            {"Rückwärtslaufen", typeof(Rueckwaertslaufen)},
            {"Runterhauen", typeof(Runterhauen)},
            {"Sahne schlagen", typeof(SahneSchlagen)},
            {"Saug-Darts", typeof(SaugDarts)},
            {"Sachen merken", typeof(SachenMerken)},
            {"Sachen treffen", typeof(SachenTreffen)},
            {"Sägen", typeof(Saegen)},
            {"Saugen", typeof(Saugen)},
            {"Schätzen", typeof(Schaetzen)},
            {"Schätzrechnen", typeof(Schaetzrechnen)},
            {"Schätz-Sägen", typeof(SchaetzSaegen)},
            {"Scharade", typeof(Scharade)},
            {"Schatzsuche", typeof(Schatzsuche)},
            {"Schaufel-Duell", typeof(SchaufelDuell)},
            {"Schaukel-Weitsprung", typeof(SchaukelWeitsprung)},
            {"Schaukel-Wurf", typeof(SchaukelWurf)},
            {"Scheibenklettern", typeof(Scheibenklettern)},
            {"Schieben & Werfen", typeof(SchiebenUndWerfen)},
            {"Schlägerwechsel", typeof(Schlaegerwechsel)},
            {"Schlitten fahren", typeof(SchlittenFahren)},
            {"Schmecken", typeof(Schmecken)},
            {"Schmetterlinge", typeof(Schmetterlinge)},
            {"Schminken", typeof(Schminken)},
            {"Schmirgeln", typeof(Schmirgeln)},
            {"Schnappen", typeof(Schnappen)},
            {"Schneeballschlacht", typeof(Schneeballschlacht)},
            {"Schneiden", typeof(Schneiden)},
            {"Schnibbeln", typeof(Schnibbeln)},
            {"Schnips-Duell", typeof(SchnipsDuell)},
            {"Schnitzelgrube", typeof(Schnitzelgrube)},
            {"Schnitzelgruben-Duell", typeof(SchnitzelgrubenDuell)},
            {"Schrauben", typeof(Schrauben)},
            {"Schreiben", typeof(Schreiben)},
            {"Schubkarre", typeof(Schubkarre)},
            {"Schubkarren-Staffel", typeof(SchubkarrenStaffel)},
            {"Schütten", typeof(Schuetten)},
            {"Schweißen", typeof(Schweissen)},
            {"Schwimmathlon", typeof(Schwimmathlon)},
            {"Schwingen", typeof(Schwingen)},
            {"Scrabble", typeof(Scrabble)},
            {"Scrooser", typeof(Scrooser)},
            {"Seil-Ball" , typeof(SeilBall)},
            {"Seilchenspringen" , typeof(Seilchenspringen)},
            {"Seile", typeof(Seile)},
            {"Sektflaschen öffnen", typeof(SektflaschenOeffnen)},
            {"Serien", typeof(Serien)},
            {"Sessel-Ball", typeof(SesselBall)},
            {"Setzen, 10!", typeof(Setzen10)},
            {"Shuffleboard", typeof(Shuffleboard)},
            {"Shut The Box", typeof(ShutTheBox)},
            {"Sitzen", typeof(Sitzen)},
            {"Sitzfußball", typeof(Sitzfussball)},
            {"Skateboard-Ball", typeof(SkateboardBall)},
            {"Skateboard-Wurf", typeof(SkateboardWurf)},
            {"Skee Ball", typeof(SkeeBall)},
            {"Skylines", typeof(Skylines)},
            {"Slashpipe", typeof(Slashpipe)},
            {"Slow-Stacking", typeof(SlowStacking)},
            {"Socken Sortieren", typeof(SockenSortieren)},
            {"Solo-Tischtennis", typeof(SoloTischtennis)},
            {"Song-Battle", typeof(SongBattle)},
            {"Songtexte", typeof(Songtexte)},
            {"Spaghetti", typeof(Spaghetti)},
            {"Sortieren", typeof(Sortieren)},
            {"Sparschwein leeren", typeof(SparschweinLeeren)},
            {"Speed-Badminton", typeof(SpeedBadminton)},
            {"Speedcourt", typeof(Speedcourt)},
            {"Speed-Darts", typeof(SpeedDarts)},
            {"Speed-Klettern", typeof(SpeedKlettern)},
            {"Speedstacking", typeof(Speedstacking)},
            {"Spielfelder", typeof(Spielfelder)},
            {"Spitz, pass auf!", typeof(SpitzPassAuf)},
            {"Sportarten", typeof(Sportarten)},
            {"Springball", typeof(Springball)},
            {"Sprossenwand", typeof(Sprossenwand)},
            {"Squash-Beachball", typeof(SquashBeachball)},
            {"Städte finden", typeof(StaedteFinden)},
            {"Stand-Hochsprung", typeof(StandHochsprung)},
            {"Stange halten", typeof(StangeHalten)},
            {"Stange werfen", typeof(StangeWerfen)},
            {"Stapel-Bagger", typeof(StapelBagger)},
            {"Stapel-Kran", typeof(StapelKran)},
            {"Stapeln", typeof(Stapeln)},
            {"Stapler-Basketball", typeof(StaplerBasketball)},
            {"Stapler-Drei-Gewinnt", typeof(StaplerDreiGewinnt)},
            {"Stapler-Puzzle", typeof(StaplerPuzzle)},
            {"Stehen", typeof(Stehen)},
            {"Steine flitschen", typeof(SteineFlitschen)},
            {"Stelzmeterschießen", typeof(Stelzmeterschiessen)},
            {"Stimmen erkennen", typeof(StimmenErkennen)},
            {"Stimmt's", typeof(Stimmts)},
            {"Stimmt's Deluxe", typeof(StimmtsDeluxe)},
            {"Street Racket", typeof(StreetRacket)},
            {"Strickleiter", typeof(Strickleiter)},
            {"Strohhalm fangen", typeof(StrohhalmFangen)},
            {"Stütz-Rennen", typeof(StuetzRennen)},
            {"Süßigkeiten", typeof(Suessigkeiten)},
            {"Surfen", typeof(Surfen)},
            {"Swincar", typeof(Swincar)},
            {"Tackern", typeof(Tackern)},
            {"Tanzen", typeof(Tanzen) },
            {"Taschenlampe", typeof(Taschenlampe) },
            {"Tauziehen", typeof(Tauziehen) },
            {"Tchoukball", typeof(Tchoukball)},
            {"Tejo", typeof(Tejo)},
            {"Tennis", typeof(Tennis)},
            {"Tennis-Bowling", typeof(TennisBowling)},
            {"Teppich verlegen", typeof(TeppichVerlegen)},
            {"Text-Aufgaben", typeof(TextAufgaben)},
            {"Tierfelle", typeof(Tierfelle)},
            {"Tier-Morphs", typeof(TierMorphs)},
            {"Tier-Umrisse", typeof(TierUmrisse)},
            {"Tisch-Curling", typeof(TischCurling)},
            {"Tischdecke", typeof(Tischdecke)},
            {"Tisch-Schnipsen", typeof(TischSchnipsen)},
            {"Tisch-Shuffleboard", typeof(TischShuffleboard)},
            {"Tinger", typeof(Tinger)},
            {"Tischtennis", typeof(Tischtennis)},
            {"Tischtennis-Maschine", typeof(TischtennisMaschine)},
            {"Tischtennis-Rundlauf", typeof(TischtennisRundlauf)},
            {"Tischtennis-Squash", typeof(TischtennisSquash)},
            {"Tisch-Titschen", typeof(TischTitschen)},
            {"Tisch-Tor", typeof(TischTor)},
            {"Titelmusik", typeof(Titelmusik)},
            {"Titschen", typeof(Titschen)},
            {"Töne merken", typeof(ToeneMerken)},
            {"Tomahawk", typeof(Tomahawk)},
            {"Tomaten", typeof(Tomaten)},
            {"Ton-Bild-Schere", typeof(TonBildSchere)},
            {"Tore", typeof(Tore)},
            {"Torwand", typeof(Torwand)},
            {"Trampolin-Weitsprung", typeof(TrampolinWeitsprung)},
            {"Transportieren", typeof(Transportieren)},
            {"Treffen", typeof(Treffen)},
            {"Treppen steigen", typeof(TreppenSteigen)},
            {"Tretathlon", typeof(Tretathlon)},
            {"Tretsack", typeof(Tretsack)},
            {"Tret-Roller", typeof(TretRoller)},
            {"Tret-Scooter", typeof(TretScooter)},
            {"Triker", typeof(Triker)},
            {"Trinken", typeof(Trinken)},
            {"Tri-Scooter", typeof(TriScooter)},
            {"Trou Madame", typeof(TrouMadame)},
            {"Türen", typeof(Tueren)},
            {"Ultimate Dodgeball", typeof(UltimateDodgeball)},
            {"Umdrehen", typeof(Umdrehen)},
            {"Umdrehungen", typeof(Umdrehungen)},
            {"Umklappen", typeof(Umklappen)},
            {"Um-Pusten", typeof(UmPusten)},
            {"Umschütten", typeof(Umschuetten)},
            {"Unsichtball", typeof(Unsichtball)},
            {"Untersetzer", typeof(Untersetzer)},
            {"Unterwaser-Puzzle", typeof(UnterwaserPuzzle)},
            {"Upside-Down", typeof(UpsideDown)},
            {"Vater-Mutter-Kind", typeof(VaterMutterKind)},
            {"Verkabeln", typeof(Verkabeln)},
            {"Versenken", typeof(Versenken)},
            {"Vier gewinnt Turm", typeof(VierGewinntTurm)},
            {"Völkerball", typeof(Voelkerball)},
            {"Volley", typeof(Volley)},
            {"Volleyball", typeof(Volleyball)},
            {"Vorbeikommen", typeof(Vorbeikommen)},
            {"Vornamen", typeof(Vornamen)},
            {"Wand-Becher-Ball", typeof(WandBecherBall)},
            {"Wann war das Foto?", typeof(WannWarDasFoto)},
            {"Wann war der Song?", typeof(WannWarDerSong)},
            {"Wann war die Sendung?", typeof(WannWarDieSendung)},
            {"Warenkorb", typeof(Warenkorb)},
            {"Was passt nicht?", typeof(WasPasstNicht)},
            {"Wasser abgiessen", typeof(WasserAbgiessen)},
            {"Wasserbasketball", typeof(Wasserbasketball)},
            {"Wasserpumpe", typeof(Wasserpumpe)},
            {"Wasser-Rennen", typeof(WasserRennen)},
            {"Wasser-Staffel", typeof(WasserStaffel)},
            {"Wasser schleppen", typeof(WasserSchleppen)},
            {"Wasserthlon", typeof(Wasserthlon)},
            {"Wedeln", typeof(Wedeln)},
            {"Wegbowlen", typeof(Wegbowlen)},
            {"Wegziehen", typeof(Wegziehen)},
            {"Weihnachtsbaum werfen", typeof(WeihnachtsbaumWerfen)},
            {"Weihnachtsmarkt", typeof(Weihnachtsmarkt)},
            {"Weintrauben", typeof(Weintrauben)},
            {"Wende-Rennen", typeof(WendeRennen)},
            {"Wer erkennt mehr?", typeof(WerErkenntMehr)},
            {"Wer fehlt?", typeof(WerFehlt)},
            {"Werfen-Titschen-Fangen", typeof(WerfenTitschenFangen)},
            {"Wer ist älter?", typeof(WerIstAelter)},
            {"Wer ist das?", typeof(WerIstDas)},
            {"Wer liebt wen?", typeof(WerLiebtWen)},
            {"Wer sind die?", typeof(WerSindDie)},
            {"Wer war das mal?", typeof(WerWarDasMal)},
            {"Wer war mal..?", typeof(WerWarMal)},
            {"Wer weiß mehr?", typeof(WerWeissMehr)},
            {"Wer weiß mehr? (Team-Mode)", typeof(WerWeissMehrTeamMode)},
            {"Wie viel wiegt..?", typeof(WieVielWiegt)},
            {"Wilhelm Tell", typeof(WilhelmTell)},
            {"Windmühle", typeof(Windmuehle)},
            {"Wörter finden", typeof(WoerterFinden)},
            {"Wörter fühlen", typeof(WoerterFuehlen) },
            {"Wörter laufen", typeof(WoerterLaufen) },
            {"Wo ist das?", typeof(WoIstDas) },           
            {"Wo ist die Mitte?", typeof(WoIstDieMitte) },
            {"Wo liegt Was?", typeof(WoLiegtWas)},
            {"Workout Bike", typeof(WorkoutBike)},
            {"Wo und wann?", typeof(WoUndWann)},
            {"Wo und wie weit?", typeof(WoUndWieWeit)},
            {"Wurf-Katapult", typeof(WurfKatapult)},
            {"Wurf-Reversi", typeof(WurfReversi)},
            {"XRay-Rennen", typeof(XRayRennen)},
            {"Zählen", typeof(Zaehlen)},
            {"Zahlen drehen", typeof(ZahlenDrehen)},
            {"Zahlen fangen", typeof(ZahlenFangen)},
            {"Zahlen-Rennen", typeof(ZahlenRennen)},
            {"Zahlen schreiben", typeof(ZahlenSchreiben)},
            {"Zahlenwörter", typeof(Zahlenwoerter)},
            {"Zeitungen austragen", typeof(ZeitungenAustragen)},
            {"Zeitzonen", typeof(Zeitzonen)},
            {"Zick-Zack", typeof(ZickZack)},
            {"Ziel-Flitschen", typeof(ZielFlitschen)},
            {"Ziesel", typeof(Ziesel)},
            {"Ziesel-Duell", typeof(ZieselDuell)},
            {"Ziesel-Staffel", typeof(ZieselStaffel)},
            {"Zollstock", typeof(Zollstock)},
            {"Zorbing-Duell", typeof(ZorbingDuell)},
            {"Zorbing-Karambolage", typeof(ZorbingKarambolage)},
            {"Zuordnen", typeof(Zuordnen)}
        };

    }
}
